version: 2

sources:
  - name: source
    tables:
      - name: source_users
        columns:
          - name: _id
            data_type: character varying
          - name: visitedat
            data_type: timestamp without time zone
          - name: createdat
            data_type: timestamp without time zone
          - name: updatedat
            data_type: timestamp without time zone
          - name: __v
            data_type: integer
          - name: __hevo__database_name
            data_type: character varying
          - name: __hevo_id
            data_type: character varying
          - name: __hevo__ingested_at
            data_type: bigint
          - name: __hevo__loaded_at
            data_type: bigint
          - name: __hevo__marked_deleted
            data_type: boolean
          - name: __hevo__source_modified_at
            data_type: bigint
          - name: campaigns
            data_type: super
          - name: assets
            data_type: super
          - name: wallets
            data_type: super
          - name: partners
            data_type: super
          - name: externalid
            data_type: character varying
          - name: name
            data_type: character varying
          - name: email
            data_type: character varying
          - name: settings
            data_type: super
          - name: deleteat
            data_type: timestamp without time zone
          - name: applicationids
            data_type: super
          - name: verifiedat
            data_type: timestamp without time zone
          - name: unverifiedemail
            data_type: character varying
          - name: applicatonids
            data_type: super

      - name: source_organization_users
        columns:
          - name: _id
            data_type: character varying
          - name: userid
            data_type: character varying
          - name: organizationid
            data_type: character varying
          - name: __v
            data_type: integer
          - name: __hevo__database_name
            data_type: character varying
          - name: __hevo_id
            data_type: character varying
          - name: __hevo__ingested_at
            data_type: bigint
          - name: __hevo__loaded_at
            data_type: bigint
          - name: __hevo__marked_deleted
            data_type: boolean
          - name: __hevo__source_modified_at
            data_type: bigint
          - name: createdat
            data_type: timestamp without time zone
          - name: updatedat
            data_type: timestamp without time zone
          - name: terms
            data_type: super
          - name: deletedat
            data_type: timestamp without time zone

